/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.8
 * Generated at: 2023-05-31 16:28:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.clients;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class pagoEnLinea_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>Logistics - Pasarela de Pagos</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"../../static/img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Icon Font Stylesheet -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"../../static/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"../../static/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"../../static/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"../../static/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container-xxl position-relative bg-white d-flex p-0\">\r\n");
      out.write("        <!-- Spinner Start -->\r\n");
      out.write("        <div id=\"spinner\" class=\"show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center\">\r\n");
      out.write("            <div class=\"spinner-border text-primary\" style=\"width: 3rem; height: 3rem;\" role=\"status\">\r\n");
      out.write("                <span class=\"sr-only\">Cargando...</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Spinner End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Payment Start -->\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row h-100 align-items-center justify-content-center\" style=\"min-height: 100vh;\">\r\n");
      out.write("                <div class=\"col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4\">\r\n");
      out.write("                    <div class=\"bg-light rounded p-4 p-sm-5 my-4 mx-3\">\r\n");
      out.write("                        <div class=\"d-flex align-items-center justify-content-between mb-3\">\r\n");
      out.write("                            <a href=\"http://localhost:8080/Gestion_Eventos/templates/clients/mostrarEventos.jsp\" class=\"\">\r\n");
      out.write("                                <h3 class=\"text-primary\"><i class=\"fa me-2\"></i>Logistic</h3>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <h3>Pagar</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-floating mb-3\">\r\n");
      out.write("                            <select class=\"form-select\" id=\"paymentMethod\" onchange=\"showPaymentFields()\">\r\n");
      out.write("                                <option value=\"\" selected disabled>Selecciona el Método de Pago</option>\r\n");
      out.write("                                <option value=\"creditCard\">Tarjeta de Crédito</option>                                \r\n");
      out.write("                                <option value=\"pse\">PSE</option>                                \r\n");
      out.write("                            </select>\r\n");
      out.write("                            <label for=\"paymentMethod\">Método de Pago</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Credit Card Fields -->\r\n");
      out.write("                        <div id=\"creditCardFields\" style=\"display: none;\">\r\n");
      out.write("                            <div class=\"form-floating mb-3\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"cardNumber\" placeholder=\"1234 5678 9012 3456\">\r\n");
      out.write("                                <label for=\"cardNumber\">Número de Tarjeta</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-floating mb-3\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"cardHolderName\" placeholder=\"Juan Pérez\">\r\n");
      out.write("                                <label for=\"cardHolderName\">Nombre del Titular</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-floating mb-3\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"cardExpiration\" placeholder=\"MM/AA\">\r\n");
      out.write("                                <label for=\"cardExpiration\">Fecha de Vencimiento</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-floating mb-3\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"cardCVV\" placeholder=\"123\">\r\n");
      out.write("                                <label for=\"cardCVV\">CVV</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-floating mb-3\">\r\n");
      out.write("                                <select class=\"form-select\" id=\"installments\" aria-label=\"Número de Cuotas\">                                    \r\n");
      out.write("                                    <option value=\"6\">6 cuotas</option>\r\n");
      out.write("                                    <option value=\"12\">12 cuotas</option>\r\n");
      out.write("                                    <option value=\"18\">18 cuotas</option>\r\n");
      out.write("                                    <option value=\"24\">24 cuotas</option>\r\n");
      out.write("                                    <option value=\"30\">30 cuotas</option>\r\n");
      out.write("                                    <option value=\"36\">36 cuotas</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                                <label for=\"installments\">Número de Cuotas</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                                               \r\n");
      out.write("                        \r\n");
      out.write("                        <!-- PSE Fields -->\r\n");
      out.write("                        <div id=\"pseFields\" style=\"display: none;\">\r\n");
      out.write("                            <div class=\"form-floating mb-3\">\r\n");
      out.write("                                <select class=\"form-select\" id=\"psePersonType\">\r\n");
      out.write("                                    <option value=\"\" selected disabled>Selecciona el Tipo de Persona</option>\r\n");
      out.write("                                    <option value=\"natural\">Persona Natural</option>\r\n");
      out.write("                                    <option value=\"juridica\">Persona Jurídica</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                                <label for=\"psePersonType\">Tipo de Persona</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-floating mb-3\">\r\n");
      out.write("                                <select class=\"form-select\" id=\"bankSelect\">\r\n");
      out.write("                                    <option value=\"\" selected disabled>Selecciona un Banco</option>\r\n");
      out.write("                                    <option value=\"bancoAgrario\">Banco Agrario</option>\r\n");
      out.write("                                    <option value=\"bancoAVVillas\">Banco AV Villas</option>\r\n");
      out.write("                                    <option value=\"bancoCajaSocial\">Banco Caja Social</option>\r\n");
      out.write("                                    <option value=\"bancoColpatria\">Banco Colpatria</option>\r\n");
      out.write("                                    <option value=\"bancoDavivienda\">Banco Davivienda</option>\r\n");
      out.write("                                    <option value=\"bancoBogota\">Banco de Bogotá</option>\r\n");
      out.write("                                    <option value=\"bancoOccidente\">Banco de Occidente</option>\r\n");
      out.write("                                    <option value=\"bancoGNBSudameris\">Banco GNB Sudameris</option>\r\n");
      out.write("                                    <option value=\"bancoPichincha\">Banco Pichincha S.A.</option>\r\n");
      out.write("                                    <option value=\"bancoPopular\">Banco Popular</option>\r\n");
      out.write("                                    <option value=\"bancoProcredit\">Banco Procredit</option>\r\n");
      out.write("                                    <option value=\"bancolombia\">Bancolombia</option>\r\n");
      out.write("                                    <option value=\"bancoomeva\">Bancoomeva S.A.</option>\r\n");
      out.write("                                    <option value=\"bbvaColombia\">BBVA Colombia S.A.</option>\r\n");
      out.write("                                    <option value=\"citibank\">Citibank</option>\r\n");
      out.write("                                    <option value=\"itau\">Itaú</option>\r\n");
      out.write("                                    <option value=\"bancoFalabella\">Banco Falabella</option>\r\n");
      out.write("                                    <option value=\"nequi\">Nequi</option>\r\n");
      out.write("                                    <option value=\"daviplata\">Daviplata</option>\r\n");
      out.write("                                    <option value=\"movii\">Movii</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                                <label for=\"bankSelect\">Banco</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-floating mb-3\">\r\n");
      out.write("                                <input type=\"email\" class=\"form-control\" id=\"pseEmail\" placeholder=\"nombre@ejemplo.com\">\r\n");
      out.write("                                <label for=\"pseEmail\">Correo Electrónico</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>  \r\n");
      out.write("                        \r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary py-3 w-100 mb-4\">Realizar Pago</button>\r\n");
      out.write("                        <p class=\"text-center mb-0\">¿Necesitas ayuda? <a href=\"\">Contáctanos</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Payment End -->\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- JavaScript Libraries -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"../../static/lib/chart/chart.min.js\"></script>\r\n");
      out.write("    <script src=\"../../static/lib/easing/easing.min.js\"></script>\r\n");
      out.write("    <script src=\"../../static/lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"../../static/lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"../../static/lib/tempusdominus/js/moment.min.js\"></script>\r\n");
      out.write("    <script src=\"../../static/lib/tempusdominus/js/moment-timezone.min.js\"></script>\r\n");
      out.write("    <script src=\"../../static/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"../../static/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function showPaymentFields() {\r\n");
      out.write("            var paymentMethod = document.getElementById(\"paymentMethod\").value;\r\n");
      out.write("            var creditCardFields = document.getElementById(\"creditCardFields\");            \r\n");
      out.write("            var pseFields = document.getElementById(\"pseFields\");            \r\n");
      out.write("\r\n");
      out.write("            creditCardFields.style.display = \"none\";            \r\n");
      out.write("            pseFields.style.display = \"none\";\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            if (paymentMethod === \"creditCard\") {\r\n");
      out.write("                creditCardFields.style.display = \"block\";\r\n");
      out.write("            } else if (paymentMethod === \"pse\") {\r\n");
      out.write("                pseFields.style.display = \"block\";\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
